target-version = "py310"

exclude = [
  "noxus_sdk/templates/cookiecutter-plugin/**",
]

[lint]
ignore = ["F401", "F541", "E722", "F841", "E402", "F811", "F403", "E741", "E401", "E731", "G004"]
extend-select = ["T201"]
exclude = ["noxus_sdk/templates/**"]

[lint.per-file-ignores]
"**/{tests,docs,tools}/*" = ["E402", "T201", "S101", "PLR2004"]
"examples/*" = ["T201"]

[format]
exclude = ["noxus_sdk/templates/**"]
